import { Handshake, ShieldCheck, Users } from "lucide-react";
import { DemoNotice } from "@/components/demo-notice";
import { PageHero } from "@/components/page-hero";
import { SubmissionForm } from "@/components/submission-form";

export const metadata = { title: "Associe-se", description: "Entenda a associação ao Sindicomar e solicite contato com a equipe." };

export default function MembershipPage() {
  return <main id="conteudo"><PageHero eyebrow="Associe-se" title="Participe de uma entidade feita para fortalecer o comércio." description="Conheça a diferença entre representação e associação e solicite uma conversa para entender benefícios, condições e próximos passos." /><section className="content-section"><div className="shell narrow-content"><DemoNotice /><div className="feature-grid membership-benefits"><article><Users /><h3>Mais representatividade</h3><p>Participação mais próxima nas pautas coletivas e institucionais.</p></article><article><ShieldCheck /><h3>Orientação organizada</h3><p>Acesso aos canais e serviços conforme as condições aprovadas.</p></article><article><Handshake /><h3>Conexões e benefícios</h3><p>Parcerias, capacitações e oportunidades vigentes para a empresa.</p></article></div><div className="prose-grid"><div><span className="eyebrow">Como funciona</span><h2>Uma solicitação simples, seguida por atendimento humano.</h2></div><div className="steps-list"><div><span>1</span><p><strong>Envie os dados da empresa</strong>CNPJ, atividade, município e responsável.</p></div><div><span>2</span><p><strong>Receba seu protocolo</strong>O pedido fica registrado no painel.</p></div><div><span>3</span><p><strong>Converse com a equipe</strong>Benefícios, valores e documentos serão explicados.</p></div></div></div></div></section><section className="content-section surface-section"><div className="shell form-layout"><div><span className="eyebrow">Solicitar associação</span><h2>Comece uma conversa com o Sindicomar.</h2><p>O envio não conclui a associação. A equipe analisará os dados e apresentará as condições válidas.</p><ul className="check-list"><li>Retorno pelo canal escolhido</li><li>Sem conclusão automática de enquadramento</li><li>Dados mantidos conforme a Política de Privacidade</li></ul></div><div className="form-card"><SubmissionForm kind="membership" /></div></div></section></main>;
}
