import { Handshake, ShieldCheck, Users } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { SubmissionForm } from "@/components/submission-form";

export const metadata = { title: "Associe-se", description: "Aproxime sua empresa do Sindicomar e solicite contato com a equipe." };

export default function MembershipPage() {
  return <main id="conteudo"><PageHero eyebrow="Associe-se" title="Sua empresa mais próxima de quem representa o comércio." description="A associação fortalece a participação empresarial e cria uma relação direta com a entidade patronal." />
    <section className="content-section"><div className="shell narrow-content"><div className="section-heading"><div><span className="eyebrow">Participação empresarial</span><h2>Mais proximidade com as pautas e iniciativas do setor.</h2></div><p>A equipe apresenta as condições vigentes e orienta a empresa durante todo o processo.</p></div><div className="feature-grid membership-benefits"><article><Users /><h3>Participação</h3><p>Maior proximidade com debates, agendas e pautas coletivas do comércio.</p></article><article><ShieldCheck /><h3>Orientação</h3><p>Acesso aos canais e serviços da entidade conforme as condições de atendimento.</p></article><article><Handshake /><h3>Relacionamento</h3><p>Conexão com empresas, instituições e oportunidades relevantes para o setor.</p></article></div><div className="prose-grid"><div><span className="eyebrow">Como funciona</span><h2>Um processo simples, conduzido pela equipe.</h2></div><div className="steps-list"><div><span>1</span><p><strong>Envie os dados da empresa</strong>Informe CNPJ, atividade, município e responsável.</p></div><div><span>2</span><p><strong>Receba o contato</strong>A equipe apresenta condições, documentos e benefícios disponíveis.</p></div><div><span>3</span><p><strong>Formalize a participação</strong>Após a análise, a empresa decide sobre a associação.</p></div></div></div></div></section>
    <section className="content-section surface-section"><div className="shell form-layout"><div><span className="eyebrow">Solicitar contato</span><h2>Comece uma conversa com o Sindicomar.</h2><p>Preencha os dados para que a equipe compreenda o perfil da empresa e organize o atendimento.</p><ul className="check-list"><li>Atendimento individual</li><li>Explicação das condições vigentes</li><li>Retorno pelo canal escolhido</li></ul></div><div className="form-card"><SubmissionForm kind="membership" /></div></div></section>
  </main>;
}
