import { CheckCircle2, CircleHelp, SearchCheck } from "lucide-react";
import { DemoNotice } from "@/components/demo-notice";
import { PageHero } from "@/components/page-hero";
import { SubmissionForm } from "@/components/submission-form";

export const metadata = { title: "Representatividade e enquadramento", description: "Entenda a representação sindical patronal e solicite análise de enquadramento." };

export default function RepresentationPage() {
  return <main id="conteudo"><PageHero eyebrow="Representatividade" title="Sua empresa é representada pelo Sindicomar?" description="O enquadramento depende da atividade preponderante, do município e das regras sindicais aplicáveis. Por isso, a análise será sempre humana." /><section className="content-section"><div className="shell narrow-content"><DemoNotice /><div className="prose-grid"><div><span className="eyebrow">Entenda a diferença</span><h2>Representação não é a mesma coisa que associação.</h2></div><div className="rich-text"><p>A representação sindical decorre do enquadramento da atividade econômica dentro da base territorial. A associação é uma decisão da empresa de participar mais diretamente da entidade e acessar benefícios nas condições aprovadas.</p><p>O portal não emitirá resposta automática. Cada solicitação será encaminhada à equipe responsável para conferência.</p></div></div><div className="comparison-grid"><article><SearchCheck /><h3>Empresa representada</h3><p>Integra a categoria econômica abrangida pela entidade, conforme atividade e território.</p></article><article><CheckCircle2 /><h3>Empresa associada</h3><p>Formaliza sua participação e acessa serviços e condições próprias da associação.</p></article><article><CircleHelp /><h3>Trabalhador procurando orientação</h3><p>O Sindicomar é patronal. Trabalhadores devem procurar a entidade laboral competente.</p></article></div></div></section><section className="content-section surface-section"><div className="shell form-layout"><div><span className="eyebrow">Análise de enquadramento</span><h2>Envie os dados básicos da empresa.</h2><p>Informe CNPJ, município e atividade principal. A resposta não é automática e não substitui parecer jurídico.</p><ul className="check-list"><li>Protocolo de recebimento</li><li>Histórico no painel administrativo</li><li>Retorno pelo canal escolhido</li></ul></div><div className="form-card"><SubmissionForm kind="classification" /></div></div></section></main>;
}
