import { CheckCircle2, CircleHelp, FileSearch, SearchCheck } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { SubmissionForm } from "@/components/submission-form";

export const metadata = { title: "Representatividade e enquadramento", description: "Entenda a representação sindical patronal e solicite uma análise de enquadramento." };

export default function RepresentationPage() {
  return <main id="conteudo"><PageHero eyebrow="Representatividade" title="Entenda a relação da sua empresa com o Sindicomar." description="A atividade econômica, a localização e a base territorial são elementos essenciais para identificar a representação sindical patronal." />
    <section className="content-section"><div className="shell narrow-content"><div className="prose-grid"><div><span className="eyebrow">Conceitos essenciais</span><h2>Representação e associação cumprem papéis diferentes.</h2></div><div className="rich-text"><p>A representação sindical está ligada ao enquadramento da atividade econômica dentro de uma base territorial. A associação é a participação voluntária da empresa na entidade, conforme suas condições e benefícios.</p><p>Quando houver dúvida, o Sindicomar analisa as informações da empresa e orienta o próximo passo pelo canal escolhido.</p></div></div><div className="comparison-grid"><article><SearchCheck /><h3>Empresa representada</h3><p>Integra a categoria econômica abrangida pela entidade de acordo com atividade e território.</p></article><article><CheckCircle2 /><h3>Empresa associada</h3><p>Participa mais diretamente da entidade e acessa serviços conforme as condições vigentes.</p></article><article><CircleHelp /><h3>Orientação ao trabalhador</h3><p>O Sindicomar representa empregadores. Demandas individuais de trabalhadores cabem à entidade laboral competente.</p></article></div></div></section>
    <section className="content-section surface-section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Como analisamos</span><h2>Um processo claro, com avaliação individual.</h2></div><p>O enquadramento não é concluído por um cálculo automático.</p></div><div className="process-grid"><div><span>01</span><FileSearch /><h3>Dados da empresa</h3><p>CNPJ, município e atividade principal ajudam a contextualizar a solicitação.</p></div><div><span>02</span><SearchCheck /><h3>Análise da atividade</h3><p>A equipe verifica os elementos relacionados à categoria econômica e ao território.</p></div><div><span>03</span><CheckCircle2 /><h3>Retorno orientado</h3><p>A empresa recebe uma resposta pelo canal indicado no formulário.</p></div></div></div></section>
    <section className="content-section"><div className="shell form-layout"><div><span className="eyebrow">Solicitar análise</span><h2>Envie os dados básicos da empresa.</h2><p>O atendimento recebe a solicitação, registra um protocolo e encaminha o caso para conferência.</p><ul className="check-list"><li>Identificação do pedido</li><li>Acompanhamento pelo atendimento</li><li>Retorno pelo canal escolhido</li></ul></div><div className="form-card"><SubmissionForm kind="classification" /></div></div></section>
  </main>;
}
