import { Building2, Handshake, Landmark, Scale, ShieldCheck, Target, Users } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { PublicLink as Link } from "@/components/public-link";

export const metadata = { title: "O Sindicomar", description: "Conheça a identidade, a atuação e a liderança do Sindicomar." };

export default function AboutPage() {
  return <main id="conteudo">
    <PageHero eyebrow="Institucional" title="Representação empresarial com presença regional." description="O Sindicomar é a entidade patronal do comércio varejista de Marechal Cândido Rondon e microrregião, filiada à Fecomércio PR." />
    <section className="content-section"><div className="shell narrow-content">
      <div className="institution-facts"><div><span>Natureza</span><strong>Entidade sindical patronal</strong></div><div><span>CNPJ</span><strong>04.702.939/0001-59</strong></div><div><span>Presidência</span><strong>Ademar Bayer</strong></div><div><span>Sede</span><strong>Marechal Cândido Rondon — PR</strong></div></div>
      <div className="prose-grid"><div><span className="eyebrow">Quem somos</span><h2>Uma voz coletiva para o comércio varejista.</h2></div><div className="rich-text"><p>O Sindicomar representa a categoria econômica patronal e atua para que os interesses comuns das empresas sejam tratados de forma organizada nas relações coletivas e institucionais.</p><p>Sua presença aproxima empresários, gestores, profissionais de RH e contadores de informações, canais de atendimento e iniciativas voltadas ao desenvolvimento do comércio regional.</p></div></div>
      <div className="value-grid"><article><Target /><h3>Representar</h3><p>Defender pautas coletivas e levar a realidade do comércio ao diálogo institucional.</p></article><article><ShieldCheck /><h3>Orientar</h3><p>Organizar o acesso a instrumentos, comunicados e atendimento responsável.</p></article><article><Handshake /><h3>Conectar</h3><p>Aproximar empresas, entidades e oportunidades relevantes para o setor.</p></article></div>
    </div></section>
    <section className="content-section surface-section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Frentes de atuação</span><h2>Uma entidade estruturada para servir ao comércio.</h2></div><p>A atuação institucional combina relações do trabalho, desenvolvimento empresarial e articulação regional.</p></div><div className="feature-grid"><article><Scale /><h3>Relações do trabalho</h3><p>Negociação coletiva, organização de instrumentos e encaminhamento de demandas empresariais.</p></article><article><Building2 /><h3>Desenvolvimento empresarial</h3><p>Informação, capacitação e aproximação com iniciativas que fortalecem a gestão.</p></article><article><Landmark /><h3>Representação institucional</h3><p>Diálogo com poder público, entidades empresariais e parceiros do Sistema Comércio.</p></article></div></div></section>
    <section className="content-section"><div className="shell leadership-layout"><div><span className="eyebrow">Liderança</span><h2>Presidência do Sindicomar</h2><p>A direção representa a entidade no relacionamento com empresas, sindicatos, instituições e poder público.</p><Link className="text-link" href="/contato">Falar com a entidade</Link></div><article className="leadership-card"><span className="leadership-monogram">AB</span><div><small>Presidente</small><h3>Ademar Bayer</h3><p>Representante do Sindicomar junto à Fecomércio PR e às articulações institucionais do comércio local.</p></div></article></div></section>
    <section className="commerce-system"><div className="shell commerce-system-inner"><Users /><div><span className="eyebrow">Sistema Comércio</span><h2>Uma entidade integrada à Fecomércio PR.</h2><p>A filiação amplia a conexão regional do Sindicomar com a rede sindical do comércio de bens, serviços e turismo no Paraná.</p></div><Link className="button button-gold" href="/servicos/beneficios-sistema-comercio">Conhecer essa conexão</Link></div></section>
  </main>;
}
