import { Building2, Handshake, Landmark, Scale, Target, Users } from "lucide-react";
import { DemoNotice } from "@/components/demo-notice";
import { PageHero } from "@/components/page-hero";

export const metadata = { title: "O Sindicomar", description: "Conheça o papel, a história e a atuação institucional do Sindicomar." };

export default function AboutPage() {
  return <main id="conteudo"><PageHero eyebrow="Institucional" title="Representação que conhece a realidade do comércio local." description="O Sindicomar é a entidade patronal do comércio varejista de Marechal Cândido Rondon e região. Sua atuação conecta defesa empresarial, negociação coletiva e apoio ao desenvolvimento." /><section className="content-section"><div className="shell narrow-content"><DemoNotice /><div className="prose-grid"><div><span className="eyebrow">Quem somos</span><h2>Uma voz coletiva para empresas de diferentes portes e segmentos.</h2></div><div className="rich-text"><p>O sindicato patronal representa a categoria econômica nas relações institucionais e coletivas. Também aproxima empresários de informação, serviços, capacitação e oportunidades que fortalecem a atividade comercial.</p><p>A razão social exata, a história institucional, a data de fundação e a base territorial serão inseridas nesta página depois da validação documental.</p></div></div><div className="value-grid"><article><Target /><h3>Missão</h3><p>Texto institucional a ser aprovado pelo Sindicomar.</p></article><article><Building2 /><h3>Visão</h3><p>Diretriz futura a ser validada pela diretoria.</p></article><article><Handshake /><h3>Valores</h3><p>Princípios de atuação a serem consolidados.</p></article></div></div></section><section className="content-section surface-section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Como atuamos</span><h2>Representação, orientação e articulação.</h2></div><p>Três frentes que organizam a presença do Sindicomar junto às empresas e às instituições.</p></div><div className="feature-grid"><article><Scale /><h3>Relações do trabalho</h3><p>Negociação coletiva, organização de instrumentos e encaminhamento responsável de dúvidas.</p></article><article><Users /><h3>Desenvolvimento empresarial</h3><p>Serviços, benefícios, capacitações e oportunidades aprovadas para o comércio local.</p></article><article><Landmark /><h3>Representação institucional</h3><p>Defesa de interesses comuns e diálogo com o poder público e entidades parceiras.</p></article></div></div></section><section className="content-section"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Diretoria</span><h2>Gestão e mandato.</h2></div><p>A composição completa, os cargos, as fotos e o período do mandato ainda precisam ser fornecidos.</p></div><div className="placeholder-panel"><Users size={28} /><div><h3>Conteúdo pendente</h3><p>A página está pronta para receber a diretoria validada sem necessidade de alterar o layout.</p></div></div></div></section></main>;
}
