import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { SubmissionForm } from "@/components/submission-form";
import { publicContact } from "@/data/site-content";

export const metadata = { title: "Contato", description: "Fale com o Sindicomar por WhatsApp, e-mail ou formulário com protocolo." };

export default function ContactPage() {
  const whatsappHref = publicContact.whatsapp ? `https://wa.me/${publicContact.whatsapp.replace(/\D/g, "")}?text=${encodeURIComponent("Olá, acessei o portal do Sindicomar e preciso de atendimento.")}` : "#formulario";
  return <main id="conteudo"><PageHero eyebrow="Contato e atendimento" title="Escolha o canal mais conveniente para você." description="WhatsApp, e-mail direto e formulário possuem o mesmo destaque. Solicitações pelo formulário recebem protocolo e ficam registradas." /><section className="content-section"><div className="shell"><div className="contact-options"><a href={whatsappHref} target={publicContact.whatsapp ? "_blank" : undefined} rel="noreferrer"><span><MessageCircle /></span><small>Conversa rápida</small><h2>WhatsApp</h2><p>{publicContact.whatsapp ? "Inicie o atendimento com uma mensagem contextualizada." : "Número oficial ainda precisa ser confirmado. Use o formulário por enquanto."}</p><strong>{publicContact.whatsapp ? "Abrir WhatsApp →" : "Ir ao formulário →"}</strong></a><a href={`mailto:${publicContact.email}?subject=${encodeURIComponent("Atendimento pelo site Sindicomar")}`}><span><Mail /></span><small>Seu programa de e-mail</small><h2>E-mail direto</h2><p>Envie uma mensagem usando o aplicativo de e-mail do seu dispositivo.</p><strong>{publicContact.email} →</strong></a><a href="#formulario"><span><Phone /></span><small>Registro com protocolo</small><h2>Formulário</h2><p>O contato fica no painel mesmo que a notificação por e-mail falhe.</p><strong>Preencher formulário →</strong></a></div><div className="contact-details"><span><Phone />{publicContact.phone}</span><span><MapPin />{publicContact.address}</span><small>{publicContact.note}</small></div></div></section><section className="content-section surface-section" id="formulario"><div className="shell form-layout"><div><span className="eyebrow">Formulário de atendimento</span><h2>Conte como podemos ajudar.</h2><p>Escolha o assunto, indique o canal preferido e receba um protocolo depois do registro.</p><div className="worker-guidance"><strong>Você é trabalhador?</strong><p>O Sindicomar representa empregadores. Procure o sindicato laboral competente para orientação individual.</p></div></div><div className="form-card"><SubmissionForm /></div></div></section></main>;
}
