import type { Metadata } from "next";
import { CalendarRange, CheckCircle2, Download, ExternalLink, FileClock, MapPin, Scale } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { DemoNotice } from "@/components/demo-notice";
import { DocumentStatusBadge } from "@/components/status-badge";
import { collectiveDocuments, documentTypeLabels } from "@/data/site-content";
import { getDocumentBySlug } from "@/lib/content";

export function generateStaticParams() { return collectiveDocuments.map((document) => ({ slug: document.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const document = getDocumentBySlug((await params).slug); if (!document) return {}; return { title: document.title, description: document.summary, openGraph: { title: document.title, description: document.summary, images: [] }, twitter: { title: document.title, description: document.summary, images: [] } }; }

export default async function DocumentPage({ params }: { params: Promise<{ slug: string }> }) {
  const document = getDocumentBySlug((await params).slug); if (!document) notFound();
  return <main id="conteudo"><section className="detail-hero"><div className="shell detail-hero-inner"><Link className="back-link" href="/convencoes">← Voltar para convenções</Link><div className="detail-title-row"><div><span className="eyebrow">{documentTypeLabels[document.type]} · {document.year}</span><h1>{document.title}</h1><p>{document.summary}</p></div><DocumentStatusBadge status={document.status} /></div></div></section><section className="content-section"><div className="shell detail-layout"><article><DemoNotice /><section className="rich-section"><h2>Resumo aprovado</h2><p>Este espaço receberá um resumo executivo conferido por responsável autorizado. O resumo jamais substitui a leitura do instrumento oficial.</p></section><section className="rich-section"><h2>Abrangência e relações</h2><div className="metadata-grid"><div><MapPin /><span>Município</span><strong>{document.municipality}</strong></div><div><Scale /><span>Categoria</span><strong>{document.category}</strong></div><div><CalendarRange /><span>Vigência</span><strong>{document.validFrom && document.validUntil ? `${document.validFrom} a ${document.validUntil}` : "A confirmar"}</strong></div><div><FileClock /><span>Data-base</span><strong>{document.baseDate ?? "A confirmar"}</strong></div><div><CheckCircle2 /><span>Última conferência</span><strong>{new Intl.DateTimeFormat("pt-BR").format(new Date(`${document.lastReviewedAt}T12:00:00`))}</strong></div><div><ExternalLink /><span>Registro MTE</span><strong>{document.mteRegistration ?? "A confirmar"}</strong></div></div></section><section className="rich-section"><h2>Documentos relacionados</h2><div className="empty-related">Aditivos, atas e comunicados relacionados aparecerão aqui sem perder o vínculo com o instrumento principal.</div></section></article><aside className="download-panel"><span className="eyebrow">Documento oficial</span><h2>Arquivo PDF</h2><p>O arquivo somente ficará disponível depois da validação documental.</p>{document.pdfUrl ? <a className="button button-primary" href={document.pdfUrl}><Download size={18} /> Baixar PDF oficial</a> : <button className="button button-disabled" disabled><Download size={18} /> PDF aguardando validação</button>}<dl><div><dt>Tipo</dt><dd>{documentTypeLabels[document.type]}</dd></div><div><dt>Sindicato laboral</dt><dd>{document.laborUnion ?? "A confirmar"}</dd></div><div><dt>Fonte oficial</dt><dd>{document.officialSource ?? "A confirmar"}</dd></div></dl><Link className="text-link" href="/contato">Precisa de orientação?</Link></aside></div></section></main>;
}
